# Generated by Django 3.0.4 on 2020-04-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mask', '0004_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('L', 'L'), ('M', 'M'), ('S', 'S')], max_length=30, null=True),
        ),
    ]
